# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/lab1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(514, 332)
        MainWindow.setMinimumSize(QtCore.QSize(514, 332))
        MainWindow.setMaximumSize(QtCore.QSize(514, 332))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.textBrColorDispay = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrColorDispay.setEnabled(False)
        self.textBrColorDispay.setMaximumSize(QtCore.QSize(150, 150))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 101, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textBrColorDispay.setPalette(palette)
        self.textBrColorDispay.setObjectName("textBrColorDispay")
        self.horizontalLayout_12.addWidget(self.textBrColorDispay)
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setMaximumSize(QtCore.QSize(16777215, 150))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalLayout_12.addWidget(self.verticalSlider)
        self.buttonPickColor = QtWidgets.QPushButton(self.centralwidget)
        self.buttonPickColor.setMinimumSize(QtCore.QSize(0, 40))
        self.buttonPickColor.setMaximumSize(QtCore.QSize(196, 16777215))
        self.buttonPickColor.setObjectName("buttonPickColor")
        self.horizontalLayout_12.addWidget(self.buttonPickColor)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_RGB = QtWidgets.QVBoxLayout()
        self.verticalLayout_RGB.setObjectName("verticalLayout_RGB")
        self.horizontalLayout_R = QtWidgets.QHBoxLayout()
        self.horizontalLayout_R.setObjectName("horizontalLayout_R")
        self.radioButton_R = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_R.setChecked(True)
        self.radioButton_R.setObjectName("radioButton_R")
        self.horizontalLayout_R.addWidget(self.radioButton_R)
        self.lineEdit_R = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_R.setMaximumSize(QtCore.QSize(112, 25))
        self.lineEdit_R.setObjectName("lineEdit_R")
        self.horizontalLayout_R.addWidget(self.lineEdit_R)
        self.verticalLayout_RGB.addLayout(self.horizontalLayout_R)
        self.horizontalLayout_G = QtWidgets.QHBoxLayout()
        self.horizontalLayout_G.setObjectName("horizontalLayout_G")
        self.radioButton_G = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_G.setObjectName("radioButton_G")
        self.horizontalLayout_G.addWidget(self.radioButton_G)
        self.lineEdit_G = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_G.setMaximumSize(QtCore.QSize(112, 25))
        self.lineEdit_G.setText("")
        self.lineEdit_G.setObjectName("lineEdit_G")
        self.horizontalLayout_G.addWidget(self.lineEdit_G)
        self.verticalLayout_RGB.addLayout(self.horizontalLayout_G)
        self.horizontalLayout_B = QtWidgets.QHBoxLayout()
        self.horizontalLayout_B.setObjectName("horizontalLayout_B")
        self.radioButton_B = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_B.setObjectName("radioButton_B")
        self.horizontalLayout_B.addWidget(self.radioButton_B)
        self.lineEdit_B = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_B.setMaximumSize(QtCore.QSize(112, 25))
        self.lineEdit_B.setObjectName("lineEdit_B")
        self.horizontalLayout_B.addWidget(self.lineEdit_B)
        self.verticalLayout_RGB.addLayout(self.horizontalLayout_B)
        self.horizontalLayout.addLayout(self.verticalLayout_RGB)
        self.verticalLayout_Lab = QtWidgets.QVBoxLayout()
        self.verticalLayout_Lab.setObjectName("verticalLayout_Lab")
        self.horizontalLayout_L = QtWidgets.QHBoxLayout()
        self.horizontalLayout_L.setObjectName("horizontalLayout_L")
        self.radioButton_L = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_L.setObjectName("radioButton_L")
        self.horizontalLayout_L.addWidget(self.radioButton_L)
        self.lineEdit_L = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_L.setMaximumSize(QtCore.QSize(112, 25))
        self.lineEdit_L.setObjectName("lineEdit_L")
        self.horizontalLayout_L.addWidget(self.lineEdit_L)
        self.verticalLayout_Lab.addLayout(self.horizontalLayout_L)
        self.horizontalLayout_a = QtWidgets.QHBoxLayout()
        self.horizontalLayout_a.setObjectName("horizontalLayout_a")
        self.radioButton_a = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_a.setObjectName("radioButton_a")
        self.horizontalLayout_a.addWidget(self.radioButton_a)
        self.lineEdit_a = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_a.setMaximumSize(QtCore.QSize(112, 25))
        self.lineEdit_a.setObjectName("lineEdit_a")
        self.horizontalLayout_a.addWidget(self.lineEdit_a)
        self.verticalLayout_Lab.addLayout(self.horizontalLayout_a)
        self.horizontalLayout_b = QtWidgets.QHBoxLayout()
        self.horizontalLayout_b.setObjectName("horizontalLayout_b")
        self.radioButton_b = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_b.setObjectName("radioButton_b")
        self.horizontalLayout_b.addWidget(self.radioButton_b)
        self.lineEdit_b = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_b.setMaximumSize(QtCore.QSize(112, 25))
        self.lineEdit_b.setObjectName("lineEdit_b")
        self.horizontalLayout_b.addWidget(self.lineEdit_b)
        self.verticalLayout_Lab.addLayout(self.horizontalLayout_b)
        self.horizontalLayout.addLayout(self.verticalLayout_Lab)
        self.verticalLayout_CMYK = QtWidgets.QVBoxLayout()
        self.verticalLayout_CMYK.setObjectName("verticalLayout_CMYK")
        self.horizontalLayout_C = QtWidgets.QHBoxLayout()
        self.horizontalLayout_C.setObjectName("horizontalLayout_C")
        self.radioButton_C = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_C.setObjectName("radioButton_C")
        self.horizontalLayout_C.addWidget(self.radioButton_C)
        self.lineEdit_C = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_C.setMaximumSize(QtCore.QSize(112, 25))
        self.lineEdit_C.setObjectName("lineEdit_C")
        self.horizontalLayout_C.addWidget(self.lineEdit_C)
        self.verticalLayout_CMYK.addLayout(self.horizontalLayout_C)
        self.horizontalLayout_M = QtWidgets.QHBoxLayout()
        self.horizontalLayout_M.setObjectName("horizontalLayout_M")
        self.radioButton_M = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_M.setObjectName("radioButton_M")
        self.horizontalLayout_M.addWidget(self.radioButton_M)
        self.lineEdit_M = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_M.setMaximumSize(QtCore.QSize(112, 25))
        self.lineEdit_M.setObjectName("lineEdit_M")
        self.horizontalLayout_M.addWidget(self.lineEdit_M)
        self.verticalLayout_CMYK.addLayout(self.horizontalLayout_M)
        self.horizontalLayout_Y = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Y.setObjectName("horizontalLayout_Y")
        self.radioButton_Y = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_Y.setObjectName("radioButton_Y")
        self.horizontalLayout_Y.addWidget(self.radioButton_Y)
        self.lineEdit_Y = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Y.setMaximumSize(QtCore.QSize(112, 25))
        self.lineEdit_Y.setObjectName("lineEdit_Y")
        self.horizontalLayout_Y.addWidget(self.lineEdit_Y)
        self.verticalLayout_CMYK.addLayout(self.horizontalLayout_Y)
        self.horizontalLayout_K = QtWidgets.QHBoxLayout()
        self.horizontalLayout_K.setObjectName("horizontalLayout_K")
        self.radioButton_K = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_K.setObjectName("radioButton_K")
        self.horizontalLayout_K.addWidget(self.radioButton_K)
        self.lineEdit_K = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_K.setMaximumSize(QtCore.QSize(112, 25))
        self.lineEdit_K.setObjectName("lineEdit_K")
        self.horizontalLayout_K.addWidget(self.lineEdit_K)
        self.verticalLayout_CMYK.addLayout(self.horizontalLayout_K)
        self.horizontalLayout.addLayout(self.verticalLayout_CMYK)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonPickColor.setText(_translate("MainWindow", "Pick color"))
        self.radioButton_R.setText(_translate("MainWindow", "R:"))
        self.radioButton_G.setText(_translate("MainWindow", "G:"))
        self.radioButton_B.setText(_translate("MainWindow", "B:"))
        self.radioButton_L.setText(_translate("MainWindow", "L:"))
        self.radioButton_a.setText(_translate("MainWindow", "a:"))
        self.radioButton_b.setText(_translate("MainWindow", "b:"))
        self.radioButton_C.setText(_translate("MainWindow", "C:"))
        self.radioButton_M.setText(_translate("MainWindow", "M:"))
        self.radioButton_Y.setText(_translate("MainWindow", "Y:"))
        self.radioButton_K.setText(_translate("MainWindow", "K:"))
